### ISSUE TITLE
Callback err and data

### ISSUE THREAD

**Issue by btk** [aarongarvey/binance#13]
Hey, as usual I was trying out this wrapper, and before reading the documentation, my blind guess for (eg:) allOrders method was this;

```
binanceRest.allOrders('BNBBTC', (data) => {
        console.log(data);
});
```

Which does not work should have had error as first parameter, having the "error" as the first parameter looked kinda weird, wanted to give feedback about it. What about swapping them, or having an error message of "No error" in order to lead the developers blindly guessing, because in my example all I see in the console is "null" string.

Thank you for the wrapper by the way!

**Comment by aarongarvey** [comment]
Error first is the standard used/set by node core http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/

RTFM ;)

**Comment by btk** [comment]
More you learn :) Thank you.
