### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on 

### ISSUE THREAD

**Issue by iBasit** [aarongarvey/binance#15]
How can I solve this issue for streaming the API and it is also doing same for REST API?

> No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 400. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

![image](https://user-images.githubusercontent.com/34341/34584938-a7431a9e-f195-11e7-8799-118394e6ef03.png)

**Comment by aarongarvey** [comment]
That's the browser disallowing access.  Cross origin resource sharing is disabled by default in the browser(https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).  Use node.js.

**Comment by iBasit** [comment]
Do you have example demo to connect binance webstream data with GUI (reactjs)? I cant find it anywhere, just need to get started with small example
