### ISSUE TITLE
Issue with timestamp request on a buy order

### ISSUE THREAD

**Issue by aaronmagi** [aarongarvey/binance#19]
Hi,

I first create a call to check /api/v1/ticker/24hr and then try to issue a buy but I get the following error.

`buyObj { symbol: 'APPCBTC',
  side: 'BUY',
  type: 'LIMIT',
  timeInForce: 'IOC',
  quantity: '4.40760',
  price: 0.00018150460000000002,
  timestamp: 1515391995190 }`

`ERR in buy {"code":-1111,"msg":"Precision is over the maximum defined for this asset."} :: { BINANCE }`

What do I need to adjust to have this work?

Thank you

**Comment by aarongarvey** [comment]
This is an error being returned by the API, not the wrapper.  Thus, you'd probably be better off consulting Binance's docs on their API, or trying to talk to someone on their slack.  That said, my guess is the precision is probably too high on your price argument.  I'd try truncating the price to 8 decimal places.

**Comment by aaronmagi** [comment]
@aarongarvey  thanks Aaron I will give it a try.  Great name BTW !!!!

Looks like the slack channel was closed.
