### ISSUE TITLE
Retrieve all tickers at once

### ISSUE THREAD

**Issue by aloysius-pgast** [aarongarvey/binance#2]
Hi.
After discussion with Binance people on Slack, I noticed that API https://www.binance.com/api/v1/ticker/allBookTickers can be used to retrieve all tickers (hence all existing pairs). Do you think it could be a nice addition to your wrapper ?
Thanks
Regards

**Comment by aloysius-pgast** [comment]
Following API is also available https://www.binance.com/api/v1/ticker/allPrices. Both are not yet described in documentation but support confirmed that they will remain supported

**Comment by aarongarvey** [comment]
Great to know!  I will add it shortly.

**Comment by ziddey** [comment]
This is what the website uses: https://www.binance.com/exchange/public/product
Combined with the tickers, you can get similar market summaries as what many other exchanges offer. Additionally, it offers the base and quote symbols individually.

**Comment by aarongarvey** [comment]
Sorry for the delay on this.  I've been busy and Binance officially adopted their own javascript library and I wasn't sure how much usage this one would get.  I added the allBookTickers and allPrices routes.  I'm reluctant to add what the website uses as it could change.  If you want to you could monkey patch it, something like

```js
binanceRest.products = (query, callback) => {
    return binanceRest._makeRequest({}, callback, 'exchange/public/product');
}
```

**Comment by alienzed** [comment]
Here's another better supported end point
https://api.binance.com/api/v3/ticker/price

**Comment by aarongarvey** [comment]
@alienzed right, they've added that v3 route since this ticket was opened.  It's exposed in the library as `binanceRest.tickerPrice()`

**Comment by inoxidavel** [comment]
@aarongarvey That does not seem to return anything if no params are passed, nor it accepts multiple params

**Comment by aarongarvey** [comment]
@inoxidavel I just tested the route, and you're right, but it's unfortunately something I can't fix.  That's something you'll have to take up with the people maintaining binance's API and their docs.  Their documentation specifies that no symbol should return all ticker symbols: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#symbol-price-ticker  `allBookTickers` and `allPrices` are still available afaik, they just may not longer be in the official docs.

**Comment by inoxidavel** [comment]
@aarongarvey I believe it is related to the server maintenance. It seems to be retrieving data when you pass a symbol parameter (i.e., you get data for a specific pair). Hoping it will work again when the maintenance is over. Otherwise, will have to figure out all pair symbols (not hard), and make the requests one by one (also not hard, but that cannot be good for the API server).
Sorry I randomly posted here, was just trying to get confirmation the issue was not only me, and there is very little references out there

**Comment by kheeva** [comment]
why there is no any delimiter in symbol between currencies?

**Comment by hmborges** [comment]
I would like to have the symbol split in 'to' and 'from' currencies. I saw that is possible to get this information by calling this endpoint: https://www.binance.com/exchange/public/product but it returns fewer values than the https://api.binance.com/api/v3/ticker/price. Anyone knows why?

**Comment by apexearth** [comment]
> but it returns fewer values

You mean it has less symbols than the other?

Seems like it is these:
```
0: {symbol: "HSRBTC", price: "0.00041400"}
1: {symbol: "ICNETH", price: "0.00166300"}
2: {symbol: "ICNBTC", price: "0.00005742"}
3: {symbol: "HSRETH", price: "0.01247400"}
4: {symbol: "VENBNB", price: "0.14920000"}
5: {symbol: "VENBTC", price: "0.00013928"}
6: {symbol: "VENETH", price: "0.00325194"}
7: {symbol: "TRIGBTC", price: "0.00001980"}
8: {symbol: "TRIGETH", price: "0.00059400"}
9: {symbol: "TRIGBNB", price: "0.01218000"}
10: {symbol: "CHATBTC", price: "0.00000195"}
11: {symbol: "CHATETH", price: "0.00006585"}
12: {symbol: "RPXBTC", price: "0.00000224"}
13: {symbol: "RPXETH", price: "0.00005449"}
14: {symbol: "RPXBNB", price: "0.00145700"}
15: {symbol: "BCNBTC", price: "0.00000022"}
16: {symbol: "BCNETH", price: "0.00000707"}
17: {symbol: "BCNBNB", price: "0.00002000"}
18: {symbol: "VENUSDT", price: "0.00010000"}
```
You should ask Binance support.

**Comment by FWangTrading** [comment]
https://www.binance.com/exchange/public/product  is a more up-to-date list.

As of today, pairs missing on https://www.binance.com/exchange/public/product and showing up on https://api.binance.com/api/v3/ticker/price are: 

['BCCBTC', 'HSRBTC', 'ICNETH', 'SALTBTC', 'SALTETH', 'SUBBTC', 'SUBETH', 'ICNBTC', 'HSRETH', 'MODBTC', 'MODETH', 'VENBNB', 'VENBTC', 'VENETH', 'BCCETH', 'BCCUSDT', 'BCCBNB', 'WINGSBTC', 'WINGSETH', 'TRIGBTC', 'TRIGETH', 'TRIGBNB', 'CHATBTC', 'CHATETH', 'RPXBTC', 'RPXETH', 'RPXBNB', 'CLOAKBTC', 'CLOAKETH', 'BCNBTC', 'BCNETH', 'BCNBNB', 'TUSDBTC', 'TUSDETH', 'TUSDBNB', 'VENUSDT', 'PHXBTC', 'PHXETH', 'PHXBNB', 'PAXBTC', 'PAXBNB', 'PAXETH', 'USDCBNB', 'USDCBTC', 'BCHSVBTC', 'BCHSVUSDT', 'BCHSVTUSD', 'BCHSVPAX', 'BCHSVUSDC']

Remove the quote coins,  one gets:
{'SALT', 'USDC', 'SUB', 'BCC', 'ICN', 'HSR', 'BCN', 'BCHSV', 'TUSD', 'VEN', 'CLOAK', 'TRIG', 'CHAT', 'PAX', 'WINGS', 'PHX', 'MOD', 'RPX'}

Delisted coins: ['BCN', 'CHAT', 'ICN', 'TRIG', 'CLOAK', 'MOD', 'SALT', 'SUB', 'WINGS',
https://www.binance.com/en/support/articles/360017720731
https://www.binance.com/en/support/articles/360023570292

Renamed coins: ['HSR' -> 'HC', 'VEN'->'VET',  'PHX'->'PHB',  'RPX' -> 'PHX']
https://www.binance.com/en/support/articles/360012489731
https://www.binance.com/en/support/articles/360007439672
https://www.binance.com/en/support/articles/360028589091
https://www.binance.com/en/support/articles/360012507711
