### ISSUE TITLE
Updated to 1.2.0, now I can't get balances anymore

### ISSUE THREAD

**Issue by wannesdemaeght** [aarongarvey/binance#20]
.account doesn't do anything anymore, not even an error.

**Comment by wannesdemaeght** [comment]
I can confirm that this is definitely related to the update.
(other authenticated things like withdrawals do work)

Downgraded to 1.1.2, I can check my balance.
Upgraded back to 1.2.0, no response from balance checks.
Downgraded back to 1.1.2, working again...

**Comment by aarongarvey** [comment]
Hmmm...it's working for me...

**Comment by aarongarvey** [comment]
Can you show me your code?

**Comment by aarongarvey** [comment]
Oh, were you passing in a callback as the second parameter?  I accidentally committed a fix I was going to wait until 2.0 to include for the account route.  I had accidentally accepted a query object as the first parameter for the account route when it's not necessary.  I fixed it, and hadn't intended to commit it yet, but that changed the function signature.  I'll add a fix so it shouldn't cause issues if someone had the callback as the second parameter.

**Comment by aarongarvey** [comment]
Change is in, let me know if 1.2.1 fixes your issue.

**Comment by wannesdemaeght** [comment]
code: (for testing purposes, production code is obviously more elaborate)
```
Binance.account((err, data) => {
	console.log(data)
	})
```


Anyhow, tested 1.2.1, working perfectly. Thank you for the fast fix!
