### ISSUE TITLE
Time synchronization with Binance

### ISSUE THREAD

**Issue by cmroche** [aarongarvey/binance#23]
I'm seeing a number if reports with ZenBot, Gekko and the CCXT projects of Binance users getting a `Response Code 400` due to their internal system clocks skewing by more than 1 second. Apparently Binance required the timestamps on all signed requests to be within 1000ms of their internal time. The issue arises for Windows users where time syncrhronization is either turned off, or whose clocks have a large skew (as the time sync service in windows only updates once a day).

For this reason it may be a good idea to implement an NIST time sync based service directly into the binance module and use an internal clock for generating timestamps over the system clock.

For reference see the following issues 

https://github.com/askmike/gekko/issues/1663 
https://github.com/ccxt/ccxt/issues/936 

I will admit that I am unsure of the feasibility of this task, but probably we shouldn't ever update the computer's system time as part of the process.

**Comment by aarongarvey** [comment]
I think some kind of fix exactly like you've specified is outside the scope of what this library should handle.  There are other exchange APIs with similar timestamp requirements, and they're there for a reason given the unreliable nature of networks.  There are also solutions for windows that will sync your clock much more often.

That said, I think a simpler solution might be to have a setting to turn on some functionality that would incrementally increase the recvWindow should a 400 response be received, it could also retry the request, and maybe only does so if the responses from the server are returning within the time of the currently specified recvWindow.  Then again, it might just be easier for them to expose the recvWindow option in their own projects' configurations so people can do it individually if they're consistently hitting the timestamp errors.  I'd be happy to work with @askmike and @ccxt if they'd like to weigh in.

**Comment by aarongarvey** [comment]
Looking at this again now that I have some more time.  It appears I didn't grasp the entire problem as there's the additional check, `if timestamp < (serverTime + 1000)`.  Right now the timestamp is automatically set to the system time if it's not present.

I could likely add some functionality that would contact the binance API to get the server time and measure that request's round trip time.  Then use those values to calculate the drift of the system clock, and adjust all subsequent timestamps.  I guess the best approach would be to do it at some specified interval, but I don't think it should be on by default.  Could also only have it calculate the drift when receiving the first 400 response and try resending the request.  The extra round trips may not be desirable in some high speed situations though.  The other issue there is after the OS syncs time the time backward, you might end up outside the recvWindow, but that could also trigger the drift calculation and retry.  Thoughts?

**Comment by aarongarvey** [comment]
Created a timesync branch with the functionality if anyone is interested in giving it a go: https://github.com/aarongarvey/binance/commit/b83a742142b81885493354e348e391bc0d32281f

You'd just basically call `binanceRest.startTimeSync(interval_in_ms)` and it'll calculate the different and adjust the timestamps appropriately.  Or at least that's the intention, I've not done thorough testing yet.  Additionally, if desired, when a request fails, you could make a call to `binanceRest.calculateDrift()` and that'll do a one time calculation.

**Comment by Marvosg** [comment]
I got this issue as well, and my computer time is synced from the internet. It seems Binance just has a wrong system clock or clock provider. So I did not bother with my local time, I can ask Binance for their current server time.

Fixed this issue by editing the 'account' function in rest.js file from binance/lib like this:

```
account(query = {}, callback) {

    /* Ensures that we can still leave the query out, but for callback calls, this changes the
       'account' function call as 'callback' is now the second parameter, not the first. This 
       could be made backward compatible by checking if 'query' is a function and assuming
       that it is meant to be a callback function. But the 'account' function definition
       should be updated like this to enable passing the timestamp parameter yourself. */
    if (!query.timestamp) {
        query.timestamp = new Date().getTime();
    }
    return this._makeRequest(query, callback, 'api/v3/account', 'SIGNED');
}
```

Then I called the 'account' function like this:

`binanceRest.account({ timestamp: (await binanceRest.time()).serverTime }).then(...)`

(or get the Binance server time previously and not wait for a response with async in this call)

So far this method has not failed once and I can now get the Binance account balace, but it does make the account call a tiny bit longer as you have to wait for the serverTime response. The 'account' function should be updated to allow passing the 'query' parameter. The extra delay is entirely up to the user, in the way use the timestamp parameter.

**Comment by aarongarvey** [comment]
Yes, the `account` function was one of the only ones where the logic was just to create an object with a timestamp rather than rather than add it if it wasn't present.  Almost all of the other functions should work like that already.

@Marvosg Can you try the code in the timesync branch that I specified in my previous comment and see if that also fixes your issue?

**Comment by Marvosg** [comment]
@aarongarvey I tried the code in the timesync branch, called the 'startTimeSync' function after initializing binanceRest and changed the 'account' call back to default, it works. Confirming it solves the issue.

**Comment by aarongarvey** [comment]
@Marvosg If I can request your assistance one more time, I've done testing on my own but had to artificially change the timestamp.  I added a configuration option to the `binanceRest` constructor called `handleDrift`.  If you set it to true and a timestamp error is received, it will calculate the drift and then attempt the request a second time.  You don't need to use the `startTimeSync` and `endTimeSync` functions with it.  I figure I'll leave the option up to the user given their speed requirements.

**Comment by cmroche** [comment]
Finally catching up here, @aarongarvey I agree with your position. We don't want a bunch of extra round trips, syncing the drift at intervals is probably enough to make this work reliably. @Marvosg You are not the first person I've seen suggest that the Binance server times are potentially incorrect, I'm beginning to wonder myself if that is the case.... especially since this seem like a very recent issue to surface.

**Comment by aarongarvey** [comment]
Changes are in and published to npm.  Let me know what you find.  I can push an incremental version with fixes if necessary.

**Comment by cmroche** [comment]
Thanks, I'll bring this over to gekko this afternoon.

**Comment by aarongarvey** [comment]
Looks like the associated issue was closed for gekko so I'm going to assume the fix is working.

**Comment by cmroche** [comment]
@aarongarvey we only have the fix in the development branch, just sorting out the responses, but so far it looks like it isn’t causing any problems. I tested locally and was able to place test orders with the correction factor.

I’ll monitor in grip, but it seems to be functional.
