### ISSUE TITLE
Passing custom parameters to be returned back on the callback

### ISSUE THREAD

**Issue by timwillhack** [aarongarvey/binance#33]
I am writing a order manager and I need a way to keep track of orders as they enter the api and complete calling back out the callback.  I am currently adding a guid but I don't want to have to edit every function to accept passing in a new parameter that it passes back later.  Any work around you could think of?  I want the ability to track the same buy order duplicated but two totally different orders.

**Comment by aarongarvey** [comment]
Look at the newClientOrderId parameter https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade

**Comment by aarongarvey** [comment]
or maybe something like

```javascript

const createHandler = (myGuid, callback) => {

    const callbackWrapper = (err, response) => {
        callback(err, response, myGuid);
    };
    return callbackWrapper;
};

binanceRest.newOrder({ necessary: 'stuff' }, createHandler(generateGuid(), (err, response, guid) => {
    // Is this what you're looking for?
}));
```

**Comment by timwillhack** [comment]
That newClientOrderId will work great, I was stuck in 'code' world didn't
look at their api for something they accept from the client.  Thanks for
pointing that out.  The create handler would work too but might as well
just use an extra parameter into newOrder, less complex.  Once again thanks!
