### ISSUE TITLE
TypeError: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by SaKKo** [aarongarvey/binance#35]
I've been running Gekko with Binance v1.3.1
and the app stopped with this code

```
/node_modules/binance/lib/rest.js:78
if (response.statusCode === 400 && payload.code === -1021 &&
TypeError: Cannot read property 'statusCode' of undefined
```

**Comment by aarongarvey** [comment]
You don't have 1.3.1, that's not the code at line 78.

**Comment by SaKKo** [comment]
Oh... sorry, i think `npm install` didn't update my server's code... 
Thank you very much sir!
