### ISSUE TITLE
How can I track order status on WWS? Is Binance api pushes it on the callback?

### ISSUE THREAD

**Issue by vladiRoz** [aarongarvey/binance#38]
tried to look everywhere for it and I couldn't find it.
only request, just seems something trivial for an exchange api.

thanks,
Jose.

**Comment by aarongarvey** [comment]
This is not the place to be asking this type of question.  However...

It's not extremely clear but the information is in the binance API documentation https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md#order-update and https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#enum-definitions.  Try the `onUserData()` function.

**Comment by vladiRoz** [comment]
thank you!!
