### ISSUE TITLE
Why are REST options are logged to console?

### ISSUE THREAD

**Issue by jakesee** [aarongarvey/binance#39]
When running the package in Heroku, the REST call parameters (options object) is logged to the console. Do you know why this might be so? Is there anywhere you are logging to stdout? I checked the request package dependency and although it has a debug switch, it does not seem to be the culprit.

For example the user data stream keep alive sends this to the console output:

2018-01-28T14:50:39.176301+00:00 app[worker.1]: {"url":"https://api.binance.com/api/v1/userDataStream?listenKey=xxxxxx","timeout":15000,"headers":{"X-MBX-APIKEY":"xxxxxx"},"method":"PUT"}

**Comment by aarongarvey** [comment]
That is weird.  That's a debug statement I was using a while back, but as far as I can tell it's not in the current set of source code.  What version are you using?

**Comment by aarongarvey** [comment]
Ah, I see what happened.  Although it didn't get committed into source control, it was still present when I published the package to npm.  I bumped the version and made sure there were no other changes present in the working directory.  1.3.3 should be good to go.  Sorry for the inconvenience.

**Comment by jakesee** [comment]
Thanks for the quick response @aarongarvey , you have done a great job with this package. Thank you for sharing!
