### ISSUE TITLE
receiving timestamp error

### ISSUE THREAD

**Issue by vettloffah** [aarongarvey/binance#4]
`code: -1021, msg: 'Timestamp for this request is not valid.`

Receiving this from binance when using `binanceRest.account()`

**Comment by vettloffah** [comment]
I tried passing the `recvWindow` property in the constructor, but t=that didn't work. When I actually went into the NPM package and added the property to the `account` function in `rest.js` then it worked.

`account(query = {}, callback) {
        if (_.isFunction(query)) {
            callback = query;
            query = {
                timestamp: new Date().getTime(),
                recvWindow: 10000 //added this here
            }
        } else if (!query.timestamp) {
            query.timestamp = new Date().getTime();
        }

        return this._makeRequest(query, callback, 'account', 'SIGNED');
    }`

**Comment by aarongarvey** [comment]
Thanks for pointing this out.  I've made an alternate fix and will have it in shortly.

**Comment by aarongarvey** [comment]
This is now documented in the README.  You should now be able to pass in recvWindow as a property on the options object passed to the constructor.
