### ISSUE TITLE
Inconsistent open/start & close/end time parameters in the kline REST & WS data

### ISSUE THREAD

**Issue by tiagosiebler** [aarongarvey/binance#47]
Is openTime the same as startTime? If so, does the same also apply to closeTime & endTime?

https://github.com/aarongarvey/binance/blob/master/lib/beautifier.js#L18
https://github.com/aarongarvey/binance/blob/master/lib/beautifier.js#L75

What are your thoughts in normalising the differences in both beautifier sections for consistency, if they are indeed the same? It's less overhead for developers looking to combine both websocket and historic data. Right now I'm assuming they are the same, and simply changing the var in the response before passing it to the DB.

There's also these:
- quoteAssetVolume & quoteVolume
- volumeActive & quoteVolumeActive & takerBaseAssetVolume & takerQuoteAssetVolume

I assume the latter are related but I'm not sure. Thanks!

**Comment by apexearth** [comment]
Duplicate of issue #22.

I think everyone is in favor of doing this, but they want to do it as a major release so as to not break anyone's existing functionality.

**Comment by tiagosiebler** [comment]
Fair enough, I'll close this one in favour of #22. Thanks!
