### ISSUE TITLE
websocket response error

### ISSUE THREAD

**Issue by longbill** [aarongarvey/binance#5]
https://github.com/aarongarvey/binance/blob/2e50536197bc82ee99c9d06119659f46cd9c7ccd/lib/ws.js#L20

it should be `eventHandler(this._beautifier.beautify(data, data.e + 'Event'));`

**Comment by boshido** [comment]
@longbill 
Have you done the pull request ?

**Comment by boshido** [comment]
I just saw someone already did 
https://github.com/aarongarvey/binance/pull/3
