### ISSUE TITLE
websocket.close() ?

### ISSUE THREAD

**Issue by JohnBDonner** [aarongarvey/binance#53]
I may be missing something here, but is there no way to do the following?
```javascript
const ws = new Binance.BinanceWS

...

// Manually close the socket
ws.close()
```

**Comment by JohnBDonner** [comment]
Any thoughts on this? @aarongarvey @laurynas-karvelis or @apexearth

**Comment by apexearth** [comment]
When you set up a stream it returns the WebSocket object to you.
https://github.com/aarongarvey/binance/blob/master/lib/ws.js#L54

So what you can do is:

```javascript
const binanceWS = new api.BinanceWS();

const ws = binanceWS.onDepthUpdate('BNBBTC', (data) => {
    console.log(data);
});

ws.close();
```

**Comment by JohnBDonner** [comment]
@apexearth Ah of course, I had misread the documentation and thought the socket instance was returned from `new Binance.BinanceWS`... silly me 😄 

Thanks!
